version: '2'

services:
  couchbase:
    build: ./couchbase
    image: eyerdurmaz/couchbase
    ports:
      - "8091-8093:8091-8093"
      - "11210:11210"

  todo:
    build: ./app
    image: eyerdurmaz/todo
    ports:
      - "8080:8080"
    depends_on:
      - "couchbase"
    restart: always